package com.personal.marketnote.product.adapter.in.web.product.response;

import com.personal.marketnote.product.port.in.result.fulfillment.FulfillmentVendorGoodsInfoResult;

public record FasstoGoodsItemResponse(
        String godCd,
        String godType,
        String godNm,
        String godTypeNm,
        String invGodNmUseYn,
        String cstGodCd,
        String godOptCd1,
        String godOptCd2,
        String cstCd,
        String cstNm,
        String supCd,
        String supNm,
        String cateCd,
        String cateNm,
        String seasonCd,
        String genderCd,
        String godPr,
        String inPr,
        String salPr,
        String dealTemp,
        String pickFac,
        String giftDiv,
        String giftDivNm,
        String godWidth,
        String godLength,
        String godHeight,
        String makeYr,
        String godBulk,
        String godWeight,
        String godSideSum,
        String godVolume,
        String godBarcd,
        String boxWidth,
        String boxLength,
        String boxHeight,
        String boxBulk,
        String boxWeight,
        String inBoxBarcd,
        String inBoxLength,
        String inBoxHeight,
        String inBoxBulk,
        String inBoxWidth,
        String inBoxWeight,
        String inBoxSideSum,
        String boxInCnt,
        String inBoxInCnt,
        String pltInCnt,
        String origin,
        String distTermMgtYn,
        String useTermDay,
        String outCanDay,
        String inCanDay,
        String boxDiv,
        String bufGodYn,
        String loadingDirection,
        String firstInDt,
        String useYn,
        String feeYn,
        String saleUnitQty,
        String cstOneDayDeliveryYn,
        String safetyStock
) {
    public static FasstoGoodsItemResponse from(FulfillmentVendorGoodsInfoResult result) {
        return new FasstoGoodsItemResponse(
                result.godCd(),
                result.godType(),
                result.godNm(),
                result.godTypeNm(),
                result.invGodNmUseYn(),
                result.cstGodCd(),
                result.godOptCd1(),
                result.godOptCd2(),
                result.cstCd(),
                result.cstNm(),
                result.supCd(),
                result.supNm(),
                result.cateCd(),
                result.cateNm(),
                result.seasonCd(),
                result.genderCd(),
                result.godPr(),
                result.inPr(),
                result.salPr(),
                result.dealTemp(),
                result.pickFac(),
                result.giftDiv(),
                result.giftDivNm(),
                result.godWidth(),
                result.godLength(),
                result.godHeight(),
                result.makeYr(),
                result.godBulk(),
                result.godWeight(),
                result.godSideSum(),
                result.godVolume(),
                result.godBarcd(),
                result.boxWidth(),
                result.boxLength(),
                result.boxHeight(),
                result.boxBulk(),
                result.boxWeight(),
                result.inBoxBarcd(),
                result.inBoxLength(),
                result.inBoxHeight(),
                result.inBoxBulk(),
                result.inBoxWidth(),
                result.inBoxWeight(),
                result.inBoxSideSum(),
                result.boxInCnt(),
                result.inBoxInCnt(),
                result.pltInCnt(),
                result.origin(),
                result.distTermMgtYn(),
                result.useTermDay(),
                result.outCanDay(),
                result.inCanDay(),
                result.boxDiv(),
                result.bufGodYn(),
                result.loadingDirection(),
                result.firstInDt(),
                result.useYn(),
                result.feeYn(),
                result.saleUnitQty(),
                result.cstOneDayDeliveryYn(),
                result.safetyStock()
        );
    }
}
